apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-app-config
data:
  KAFKA_BROKERS: "kafka.default.svc:9092"
  KAFKA_TOPIC: "kafka-topic"
  KAFKA_CLIENT_ID: "producer-app"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-app-config
data:
  KAFKA_BROKERS: "kafka.default.svc:9092"
  KAFKA_TOPIC: "kafka-topic"
  KAFKA_CLIENT_ID: "consumer-app"
  MONGO_URI: "mongodb://mongo-service.default.svc:27017"
  MONGO_DB_NAME: "test"
  MONGO_COLLECTION: "events"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-app-config
data:
  MONGO_URI: "mongodb://mongo-service.default.svc:27017/eventsdb"
  PORT: "3000"