apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: default
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka.default.svc.cluster.local:9092"
        - name: KAFKA_CFG_BROKER_ID
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 10
          periodSeconds: 15
        volumeMounts:
        - name: kafka-data
          mountPath: /bitnami/kafka
      - name: prometheus-sidecar
        image: prom/prometheus:latest
        ports:
          - containerPort: 9090
        livenessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 15
        volumeMounts:
          - name: prometheus-config
            mountPath: /etc/prometheus/
      volumes:
      - name: kafka-data
        emptyDir: {}
      - name: prometheus-config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
spec:
  selector:
    app: kafka
  ports:
  - name: kafka
    protocol: TCP
    port: 9092
    targetPort: 9092
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090
  type: ClusterIP




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kafka
#   namespace: default
#   labels:
#     app: kafka
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka
#   template:
#     metadata:
#       labels:
#         app: kafka
#     spec:
#       containers:
#       - name: kafka
#         image: bitnami/kafka:latest
#         ports:
#         - containerPort: 9092
#         env:
#         - name: ALLOW_PLAINTEXT_LISTENER
#           value: "yes"
#         - name: KAFKA_CFG_ZOOKEEPER_CONNECT
#           value: "zookeeper:2181"
#         - name: KAFKA_CFG_LISTENERS
#           value: "PLAINTEXT://:9092"
#         - name: KAFKA_CFG_ADVERTISED_LISTENERS
#           value: "PLAINTEXT://kafka.default.svc.cluster.local:9092"
#         - name: KAFKA_CFG_BROKER_ID
#           value: "1"
#         volumeMounts:
#         - name: kafka-data
#           mountPath: /bitnami/kafka
#       - name: prometheus-sidecar
#         image: prom/prometheus:latest
#         ports:
#           - containerPort: 9090
#         volumeMounts:
#           - name: prometheus-config
#             mountPath: /etc/prometheus/
#       volumes:
#       - name: kafka-data
#         emptyDir: {}
#       - name: prometheus-config
#         configMap:
#           name: prometheus-config
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka
#   namespace: default
# spec:
#   selector:
#     app: kafka
#   ports:
#   - name: kafka
#     protocol: TCP
#     port: 9092
#     targetPort: 9092
#   - name: prometheus
#     protocol: TCP
#     port: 9090
#     targetPort: 9090
#   type: ClusterIP