apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-consumer-to-mongo
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: mongo-deployment
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-app
        - podSelector:
            matchLabels:
              app: consumer-app
      ports:
        - protocol: TCP
          port: 27017
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-producer-consumer-to-kafka
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: kafka
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: producer-app
        - podSelector:
            matchLabels:
              app: consumer-app
      ports:
        - protocol: TCP
          port: 9092
  policyTypes:
    - Ingress